feat: vscode command in remote terminal

diff --git a/zsh/zshenv b/zsh/zshenv
--- a/zsh/zshenv
+++ b/zsh/zshenv
@@ -27,3 +27,21 @@ if [ -e "$HOME/.cargo/env" ] ; then
     . "$HOME/.cargo/env"
 fi
 
+
+code () {
+	# local script=$(echo ~/.vscode-server/bin/*/bin/code(*ocNY1)) 
+    local script=$(echo ~/.vscode-server/bin/*/bin/remote-cli/code(*oc[1]N))
+	if [[ -z ${script} ]]
+	then
+		echo "VSCode remote script not found"
+		exit 1
+	fi
+    local socket=$(echo /run/user/$UID/vscode-ipc-*.sock(=ocNY1)) 
+	if [[ -z ${socket} ]]
+	then
+		echo "VSCode IPC socket not found"
+		exit 1
+	fi
+	export VSCODE_IPC_HOOK_CLI=${socket} 
+	${script} $*
+}
